name: 일반 이슈 템플릿
description: 일반적인 버그 수정, 기능 추가, 개선, 문서 작업 등에 대한 이슈를 생성할 때 사용
title: "[FEAT] 이슈 제목 작성"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        <!--
        이슈 이름 컨벤션
        [BUG] : 기존 기능의 문제를 수정하는 작업
        [FEAT] : 새로운 기능을 추가하는 작업
        [IMPR] : 기존 기능이나 코드의 개선 작업
        [DOC] : 문서 작성 및 업데이트 작업
        [OTHER] : 기타 필요한 작업
        -->

  - type: textarea
    id: description
    attributes:
      label: 💥 이슈 설명
      description: 문제 상황이나 기능 구현 배경 등 구체적인 설명을 작성해 주세요.
      placeholder: |
        - 어떤 문제가 있나요?
        - 어떤 기능을 추가하고자 하나요?
        - 예시: 버그 발생 상황이나 캡처
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 📚 할 일 목록
      description: 이 이슈에서 처리해야 할 작업들을 체크리스트로 작성해 주세요.
      placeholder: |
        - [ ] **할 일 1** : 세부 내용
        - [ ] **할 일 2** : 세부 내용
      validations:
      required: false

  - type: input
    id: related
    attributes:
      label: 🔄 관련 작업
      description: "관련된 작업이나 PR 번호가 있다면 작성해 주세요 (예: #1234)"
      placeholder: "#1234 (optional)"
    validations:
      required: false

  - type: textarea
    id: reference
    attributes:
      label: 👀 참고 사항
      description: 참고할 정보, 문서 링크 등을 작성해 주세요.
      placeholder: 관련 문서, 외부 사이트 링크 등
    validations:
      required: false

  - type: input
    id: due
    attributes:
      label: ⌛ 기한
      description: 이 이슈를 해결해야 하는 기한이 있다면 작성해 주세요.
      placeholder: "예: 2025-07-10"
    validations:
      required: false
